<?php
// Default language
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'en';
}

// Translation arrays
$lang = [
    'en' => [
        // Navbar
        'nav_home' => 'Home',
        'nav_gallery' => 'Activity Gallery',
        'nav_academic' => 'Academic Classes',
        'nav_skill' => 'Skill Classes',
        'nav_rules' => 'Rules',
        'nav_school_rules' => 'School Rules',
        'nav_parents_guidelines' => 'Parents Guidelines',
        'nav_tutors_guidelines' => 'Tutors Guidelines',
        'nav_lang_id' => 'ID',
        'nav_lang_en' => 'EN',
        
        // Footer
        'footer_desc' => 'Adventist Homeschooling Community dedicated to shaping a smart, character-driven generation that fears God.',
        'footer_menu' => 'Menu',
        'footer_contact' => 'Contact',
        'footer_admin1' => 'Registration Admin 1',
        'footer_admin2' => 'Registration Admin 2',
        'footer_treasurer' => 'Treasurer',
        'footer_rights' => 'All rights reserved.',
        
        // Homepage
        'hero_title' => 'School for <span class="highlight">Homeschool Children</span>',
        'hero_desc' => 'PKBM Bread of Life brings a homeschooling method based on collaboration between parents and school, so that every child can grow into a resilient, creative person who loves God.',
        'hero_register' => 'Register Now',
        'hero_gallery' => 'View Gallery',
        'about_badge' => 'About Us',
        'about_title' => 'About PKBM Bread of Life',
        'about_desc' => 'PKBM Bread of Life Adventist Homeschooler Community is a community-based learning center registered under a foundation with the aim of supporting non-formal education. We offer Package A, B, and C programs with high flexibility.',
        'mission_title' => '🚀 Our Mission',
        'mission_desc' => 'Building character, academic skills, and a serving heart through learning activities centered on Christ and supported by the community.',
        'model_title' => '💻 Learning Model',
        'model_desc' => 'Classes are delivered primarily through online sessions (Zoom), combined with periodic face-to-face practice sessions and community activities.',
        'programs_title' => 'Learning Programs',
        'programs_subtitle' => 'Available education levels',
        'package_a' => 'Package A (SD)',
        'package_a_desc' => 'Equivalent to Elementary School. Focus on character building and basic literacy skills.',
        'package_b' => 'Package B (SMP)',
        'package_b_desc' => 'Equivalent to Junior High. Developing interests, talents, and life skills.',
        'package_c' => 'Package C (SMA)',
        'package_c_desc' => 'Equivalent to Senior High. Preparation for higher education or entrepreneurship.',
        'gallery_preview_title' => 'Peek at Our Activities 📸',
        'gallery_preview_subtitle' => 'Snapshots of the excitement of learning at PKBM Bread of Life',
        'gallery_view_all' => 'View Full Gallery',
        'cta_title' => 'Ready to Join?',
        'cta_desc' => 'Come grow together in a loving community. New student registration is now open!',
        'cta_register' => 'Register Online Now 📝',
        'elem_badge' => '🎒 Elementary',
        'jr_badge' => '🔬 Junior High',
        'sr_badge' => '🎓 Senior High',
        
        // Gallery
        'gallery_title' => 'Activity Gallery 📸',
        'gallery_subtitle' => 'Documentation of growing and learning together. (Click photo to enlarge)',
        'tab_academic' => '🎓 Academic Classes',
        'tab_skill' => '🎨 Skill Classes',
        'sd_label' => 'SD (Grades 1-6)',
        'smp_label' => 'SMP (Grades 7-9)',
        'sma_label' => 'SMA (Grades 10-12)',
        'grade_1' => 'Grade 1',
        'grade_2' => 'Grade 2',
        'grade_3' => 'Grade 3',
        'grade_4' => 'Grade 4',
        'grade_5' => 'Grade 5',
        'grade_6' => 'Grade 6',
        'grade_7' => 'Grade 7',
        'grade_8' => 'Grade 8',
        'grade_9' => 'Grade 9',
        'no_student' => 'No Students Yet',
        'coming_soon' => 'Coming Soon!',
        'coming_soon_desc' => 'Click for information about SMA level opening.',
        'sma_info' => 'SMA Level Information',
        'sma_info_desc' => 'Apologies, SMA level documentation is not yet available.<br><br><span class="fw-bold text-dark mark" style="background: #FFC371; padding: 2px 5px; border-radius: 5px;">SMA level will open in Academic Year 2026.</span>',
        'sma_ok' => 'Got it! 👍',
        'skill_cooking' => '🍳 Cooking Class',
        'skill_worship' => '🙏 Student Worship',
        'skill_group' => '🤝 Group Activities',
        'skill_special' => '✨ Special Activities',
        
        // School Rules
        'rules_title' => 'School Rules',
        'rules_desc' => 'We expect students to follow these guidelines to create a respectful and productive online learning environment.',
        'rule_1' => 'Punctuality: Join class early or on time.',
        'rule_2' => 'Camera on: Keep your camera on during class unless the teacher allows otherwise.',
        'rule_3' => 'Use real name: Display your real name (e.g., Ester_Grade4).',
        'rule_4' => 'Chat responsibly: Use chat only for relevant questions and polite comments.',
        'rule_5' => 'Dress appropriately: Wear neat and comfortable clothing for class.',
        'rule_6' => 'No eating during sessions: Avoid eating during class, worship, or flag ceremonies out of respect.',
        'back_home' => 'Back to Home',
        
        // Parents Guidelines
        'parents_title' => 'Parents Guidelines',
        'parents_desc' => 'Parents are partners in learning. Your active support helps students succeed.',
        'parent_1' => 'Support your child\'s learning activities at home and encourage regular study.',
        'parent_2' => 'Attend school activities such as book readings and other events when possible.',
        'parent_3' => 'Participate in home learning tasks: assignments, journals, reflections, practical activities.',
        'parent_4' => 'Submit assignments on time according to the schedule.',
        'parent_5' => 'Accompany and assist younger children during online sessions or practical tasks.',
        
        // Tutors Guidelines
        'tutors_title' => 'Tutors Guidelines',
        'tutors_desc' => 'Tutors create a safe and engaging learning space for students. Expectations below:',
        'tutor_1' => 'Prepare lessons, materials, and activities before each Zoom class.',
        'tutor_2' => 'Start and end classes on time; include a brief prayer or devotion if appropriate.',
        'tutor_3' => 'Maintain discipline and consistency throughout the session.',
        'tutor_4' => 'Notify of schedule changes at least one day in advance (H-1).',
        'tutor_5' => 'Create a positive, interactive, Christ-centered online learning environment.',
    ],
    'id' => [
        // Navbar
        'nav_home' => 'Beranda',
        'nav_gallery' => 'Galeri Kegiatan',
        'nav_academic' => 'Kelas Akademik',
        'nav_skill' => 'Kelas Keterampilan',
        'nav_rules' => 'Peraturan',
        'nav_school_rules' => 'Peraturan Siswa',
        'nav_parents_guidelines' => 'Panduan Orang Tua',
        'nav_tutors_guidelines' => 'Panduan Tutor',
        'nav_lang_id' => 'ID',
        'nav_lang_en' => 'EN',
        
        // Footer
        'footer_desc' => 'Komunitas Homeschooling Advent yang berdedikasi untuk mencetak generasi cerdas, berkarakter, dan takut akan Tuhan.',
        'footer_menu' => 'Menu',
        'footer_contact' => 'Kontak',
        'footer_admin1' => 'Admin Pendaftaran 1',
        'footer_admin2' => 'Admin Pendaftaran 2',
        'footer_treasurer' => 'Bendahara',
        'footer_rights' => 'All rights reserved.',
        
        // Homepage
        'hero_title' => 'Sekolah bagi <br><span class="highlight">Anak Homeschool</span>',
        'hero_desc' => 'PKBM Bread of Life menghadirkan metode homeschooling berbasis kolaborasi antara orang tua dan sekolah, agar setiap anak dapat bertumbuh menjadi pribadi yang tangguh, kreatif, dan mengasihi Tuhan.',
        'hero_register' => 'Daftar Sekarang',
        'hero_gallery' => 'Lihat Galeri',
        'about_badge' => 'Tentang Kami',
        'about_title' => 'Tentang PKBM Bread of Life',
        'about_desc' => 'PKBM Bread of Life Adventist Homeschooler Community adalah pusat pembelajaran berbasis komunitas yang terdaftar di bawah yayasan dengan tujuan mendukung pendidikan non-formal. Kami menawarkan program Paket A, B, dan C dengan fleksibilitas tinggi.',
        'mission_title' => '🚀 Misi Kami',
        'mission_desc' => 'Membangun karakter, keterampilan akademik, dan hati yang melayani melalui kegiatan pembelajaran yang berpusat pada Kristus dan didukung oleh komunitas.',
        'model_title' => '💻 Model Belajar',
        'model_desc' => 'Kelas disampaikan terutama melalui sesi online (Zoom), dikombinasikan dengan sesi praktik tatap muka berkala dan kegiatan komunitas.',
        'programs_title' => 'Program Belajar',
        'programs_subtitle' => 'Jenjang pendidikan yang tersedia',
        'package_a' => 'Paket A (SD)',
        'package_a_desc' => 'Setara Sekolah Dasar. Fokus pada pembentukan karakter dan calistung dasar.',
        'package_b' => 'Paket B (SMP)',
        'package_b_desc' => 'Setara SMP. Pengembangan minat, bakat, dan keterampilan hidup (life skills).',
        'package_c' => 'Paket C (SMA)',
        'package_c_desc' => 'Setara SMA. Persiapan menuju jenjang kuliah atau dunia wirausaha.',
        'gallery_preview_title' => 'Intip Kegiatan Kami 📸',
        'gallery_preview_subtitle' => 'Cuplikan keseruan belajar di PKBM Bread of Life',
        'gallery_view_all' => 'Lihat Galeri Selengkapnya',
        'cta_title' => 'Siap Bergabung?',
        'cta_desc' => 'Mari bertumbuh bersama dalam komunitas yang penuh kasih. Pendaftaran siswa baru telah dibuka!',
        'cta_register' => 'Daftar Online Sekarang 📝',
        'elem_badge' => '🎒 Elementary',
        'jr_badge' => '🔬 Junior High',
        'sr_badge' => '🎓 Senior High',
        
        // Gallery
        'gallery_title' => 'Galeri Kegiatan 📸',
        'gallery_subtitle' => 'Dokumentasi keseruan belajar dan bertumbuh bersama. (Klik foto untuk memperbesar)',
        'tab_academic' => '🎓 Kelas Akademik',
        'tab_skill' => '🎨 Kelas Keterampilan',
        'sd_label' => 'SD (Kelas 1 - 6)',
        'smp_label' => 'SMP (Kelas 7 - 9)',
        'sma_label' => 'SMA (Kelas 10 - 12)',
        'grade_1' => 'Kelas 1',
        'grade_2' => 'Kelas 2',
        'grade_3' => 'Kelas 3',
        'grade_4' => 'Kelas 4',
        'grade_5' => 'Kelas 5',
        'grade_6' => 'Kelas 6',
        'grade_7' => 'Kelas 7',
        'grade_8' => 'Kelas 8',
        'grade_9' => 'Kelas 9',
        'no_student' => 'Belum Ada Siswa',
        'coming_soon' => 'Akan Segera Hadir!',
        'coming_soon_desc' => 'Klik untuk informasi pembukaan jenjang SMA.',
        'sma_info' => 'Informasi Jenjang SMA',
        'sma_info_desc' => 'Mohon maaf, dokumentasi tingkat SMA belum tersedia.<br><br><span class="fw-bold text-dark mark" style="background: #FFC371; padding: 2px 5px; border-radius: 5px;">Jenjang SMA baru akan dibuka Tahun Ajaran 2026.</span>',
        'sma_ok' => 'Siap, Saya Mengerti! 👍',
        'skill_cooking' => '🍳 Kelas Memasak',
        'skill_worship' => '🙏 Ibadah Siswa',
        'skill_group' => '🤝 Kegiatan Kelompok',
        'skill_special' => '✨ Kegiatan Spesial',
        
        // School Rules
        'rules_title' => 'Peraturan Sekolah',
        'rules_desc' => 'Kami mengharapkan siswa mengikuti pedoman ini untuk menciptakan lingkungan belajar online yang saling menghargai dan produktif.',
        'rule_1' => 'Tepat waktu: Bergabunglah ke kelas lebih awal atau tepat waktu.',
        'rule_2' => 'Kamera menyala: Biarkan kamera Anda tetap menyala selama kelas kecuali guru mengizinkan sebaliknya.',
        'rule_3' => 'Gunakan nama asli: Tampilkan nama asli Anda (contoh: Ester_Kelas4).',
        'rule_4' => 'Chat dengan bertanggung jawab: Gunakan obrolan hanya untuk pertanyaan yang relevan dan komentar yang sopan.',
        'rule_5' => 'Berpakaian sopan: Berpakaian rapi dan nyaman untuk kelas.',
        'rule_6' => 'Dilarang makan saat sesi: Hindari makan selama kelas, ibadah, atau upacara bendera demi rasa hormat.',
        'back_home' => 'Kembali ke Beranda',
        
        // Parents Guidelines
        'parents_title' => 'Pedoman Orang Tua',
        'parents_desc' => 'Orang tua adalah mitra dalam pembelajaran. Dukungan aktif Anda membantu siswa berhasil.',
        'parent_1' => 'Dukung kegiatan belajar anak Anda di rumah dan dorong belajar secara teratur.',
        'parent_2' => 'Hadiri kegiatan sekolah seperti pembacaan buku dan acara lainnya jika memungkinkan.',
        'parent_3' => 'Berpartisipasi dalam tugas belajar di rumah: tugas, jurnal, renungan, kegiatan praktik.',
        'parent_4' => 'Kumpulkan tugas tepat waktu sesuai jadwal.',
        'parent_5' => 'Dampingi dan bantu anak-anak yang lebih muda selama sesi online atau tugas praktik.',
        
        // Tutors Guidelines
        'tutors_title' => 'Pedoman Tutor',
        'tutors_desc' => 'Tutor menciptakan ruang belajar yang aman dan menarik bagi siswa. Harapan di bawah ini:',
        'tutor_1' => 'Siapkan pelajaran, materi, dan kegiatan sebelum setiap kelas Zoom.',
        'tutor_2' => 'Mulai dan akhiri kelas tepat waktu; sertakan doa singkat atau renungan jika sesuai.',
        'tutor_3' => 'Pertahankan disiplin dan konsistensi sepanjang sesi.',
        'tutor_4' => 'Informasikan perubahan jadwal setidaknya satu hari sebelumnya (H-1).',
        'tutor_5' => 'Ciptakan lingkungan belajar online yang positif, interaktif, dan berpusat pada Kristus.',
    ]
];

// Helper function to get translated text
function t($key) {
    global $lang;
    $current = $_SESSION['lang'] ?? 'en';
    return $lang[$current][$key] ?? $lang['en'][$key] ?? $key;
}
